[project]
name = "dl"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.11.0",
    "albumentations>=2.0.8",
    "bitsandbytes>=0.48.1",
    "cython>=3.1.6",
    "datasets>=4.3.0",
    "gdown>=5.2.0",
    "hf-xet>=1.2.0",
    "ipywidgets>=8.1.7",
    "nbformat>=5.10.4",
    "numba>=0.62.1",
    "numpy>=2.3.4",
    "opencv-python>=4.11.0.86",
    "optimum>=2.0.0",
    "pandas>=2.3.3",
    "peft>=0.17.1",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "sentencepiece>=0.2.1",
    "statsmodels>=0.14.5",
    "torch>=2.9.0",
    "torchaudio>=2.9.0",
    "torchvision>=0.24.0",
    "tqdm>=4.67.1",
    "transformers[torch]>=4.57.1",
    "ultralytics>=8.3.221",
    "wandb>=0.22.2",
    "youtokentome>=1.0.6",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]

[tool.uv.extra-build-dependencies]
      youtokentome = ["Cython"]


[tool.uv.sources]
torch = [
  { index = "pytorch-cu130" },
]
torchvision = [
  { index = "pytorch-cu130" },
]
torchaudio = [
  { index = "pytorch-cu130" },
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true
